name: Print environment variables
run-name: Testing env
on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  if: github.repository_owner == 'aws'
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: env | sort
